basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Apigo - Spec Documentation API
  version: "1.0"
paths:
  /authenticate/signIn:
    post:
      consumes:
      - application/json
      description: login to your account
      parameters:
      - description: email
        format: email
        in: query
        name: email
        type: string
        required: true
      - description: password
        format: password
        in: query
        name: password
        type: string
        required: true
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: login to account
      tags:
      - Authentication
  /authenticate/signUp:
    post:
      consumes:
      - application/json
      description: register
      parameters:
      - description: name
        format: name
        in: query
        name: name
        required: true
        type: string
      - description: email
        format: email
        in: query
        name: email
        required: true
        type: string
      - description: password
        format: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - Application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: register to account
      tags:
      - authentication
  /user/:
    get:
      consumes:
      - application/json
      description: user get all account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: user all account
      tags:
      - User Profile
  /user/profile:
    put:
      consumes:
      - application/json
      description: user update
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: name
        format: name
        in: query
        name: name
        type: string
      - description: email
        format: email
        in: query
        name: email
        type: string
      - description: password
        format: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: user account
      tags:
      - User Profile
  /user/profile/:id:
    get:
      consumes:
        - application/json
      description: user update
      parameters:
        - description: Bearer
          in: header
          name: Authorization
          required: true
          type: string
        - description: userId
          format: userId
          in: query
          name: userId
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: user account
      tags:
        - User Profile
  /books/:
    get:
      consumes:
        - application/json
      description: get data books
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: get data books
      tags:
        - Books
  /books/add/:
    post:
      consumes:
        - application/json
      description: add data books
      parameters:
        - description: title
          format: title
          in: query
          name: title
          type: string
          required: true
        - description: description
          format: description
          in: query
          name: description
          type: string
          required: true
        - description: user_id
          format: user_id
          in: query
          name: user_id
          type: string
          required: true
      produces:
        - application/json
      responses:
        "201":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: add data books
      tags:
        - Books
  /books/fetch/:id:
    get:
      consumes:
        - application/json
      description: get data books
      produces:
        - application/json
      parameters:
        - description: id
          format: id
          in: query
          name: id
          type: string
          required: true
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: get data books
      tags:
        - Books
  /books/update/:id:
    put:
      description: update data books
      consumes:
        - application/json
      produces:
        - application/json
      summary: update data books
      parameters:
        - description: id
          format: id
          in: query
          name: id
          type: string
          required: true
        - description: title
          format: title
          in: query
          name: title
          type: string
          required: true
        - description: description
          format: description
          in: query
          name: description
          type: string
          required: true
        - description: user_id
          format: user_id
          in: query
          name: user_id
          type: string
          required: true
      responses:
        "201":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
        - Books
  /books/delete/:id:
    delete:
      consumes:
        - application/json
      description: delete data books
      produces:
        - application/json
      parameters:
        - description: id
          format: id
          in: query
          name: id
          type: string
          required: true
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: delete data books
      tags:
        - Books
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
